# Generated by Django 5.0.7 on 2024-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.vecteezy.com/vector-art/22058960-no-image-available-icon', max_length=5000),
        ),
    ]
